### ISSUE TITLE
Pip: ImportError pip._internal.utils

### ISSUE THREAD

**Issue by optiz0r** [jfrog/frogbot#149]
**Describe the bug**

`frogbot scan-pull-requests` throws stack trace when scanning a pip project

**To Reproduce**

* Create a python project with requirements.txt
* Set environment variables for communication with Artifactory and Git provider, including pointing at the git repo for the python project
* Run `frogbot scan-pull-requests`

**Expected behavior**

Frogbot to run without crashing

**Screenshots**

```
-bash-4.2$ env JF_GIT_API_ENDPOINT="http://stash.example.com/rest" JF_GIT_OWNER=INFRA JF_GIT_REPO=xray-test  JF_URL=https://artifactory.dev.example.com ./frogbot scan-pull-requests
10:09:34 [🔵Info] Running Frogbot "scan-pull-requests" command 
10:09:34 [🔵Info] Auditing /tmp/jfrog.cli.temp.-1663319374-3547796160
10:09:34 [🔵Info] Detected: pip.
10:09:37 [🚨Error] pip Audit command failed: failed running command: '/tmp/jfrog.cli.temp.-1663319374-2082447499/venvdir/bin/python python /data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py --json' with error: exit status 1 - Traceback (most recent call last):
  File "/data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py", line 874, in <module>
    sys.exit(main())
  File "/data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py", line 822, in main
    user_only=args.user_only)
  File "/data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py", line 801, in get_installed_distributions
    from pip._internal.utils import misc
ImportError: No module named _internal.utils

10:09:37 [🚨Error] pip Audit command failed: failed running command: '/tmp/jfrog.cli.temp.-1663319374-2082447499/venvdir/bin/python python /data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py --json' with error: exit status 1 - Traceback (most recent call last):
  File "/data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py", line 874, in <module>
    sys.exit(main())
  File "/data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py", line 822, in main
    user_only=args.user_only)
  File "/data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py", line 801, in get_installed_distributions
    from pip._internal.utils import misc
ImportError: No module named _internal.utils
```

**Versions**

- Frogbot version: 2.3.2
- Operating system: CentOS 7.7
- JFrog Artifactory version: 7.41.7
- JFrog Xray version (version 3.29.0 or above is required):3.54.5
- python2: 2.7.5 (pip 8.1.2)
- python3: 3.6.8 (pip 9.0.3)

**Additional context**

Pip itself appears to be working fine. Packages can be installed inside user context or new virtualenvs without issue.

**Comment by eyalbe4** [comment]
Thanks for reporting this issue @optiz0r.
Will you be able to share with us a sample project that we can use to reproduce this issue? This doesn't seem to be happening on the python projects we're using.

**Comment by sverdlov93** [comment]
@optiz0r 
It looks like it took python2 instead of python3.
Can you add JFROG_CLI_LOG_LEVEL = "DEBUG" to your envs and share the logs again?

**Comment by optiz0r** [comment]
@eyalbe4 The project is trivial:

```
### bin/xray-test
#!/usr/bin/python3
import yaml
print("Hello World!")

### requirements.txt
PyYAML==3.13

### setup.py
from setuptools import setup, find_packages
 
setup(
    name="xray-test",
    version="0.1",
    description="Simple hello-world application to test xray integration in the build process",
    author="Ben Roberts",
    author_email="ben.roberts@example.com",
    url="https://example.com/xray-test",
    packages=find_packages(exclude=['tests*']),
    scripts=['bin/xray-test'],
    install_requires=['PyYAML'],
)
```

This is hosted in a bitbucket server repository. The open pull request is a noop change, adding a comment to the requirements.txt file.

@sverdlov93 with debug logs:

```
-bash-4.2$ env JFROG_CLI_LOG_LEVEL=DEBUG JF_GIT_API_ENDPOINT="http://stash.example.com/rest" JF_GIT_OWNER=INFRA JF_GIT_REPO=xray-test  JF_URL=https://artifactory.dev.example.com ./frogbot scan-pull-requests
11:18:33 [Debug] JF_INCLUDE_ALL_VULNERABILITIES is off, the value is:  
11:18:33 [🔵Info] Running Frogbot "scan-pull-requests" command 
11:18:33 [Debug] Usage Report: Sending info...
11:18:33 [Debug] Sending HTTP GET request to: https://artifactory.dev.example.com/artifactory/api/system/version
11:18:33 [Debug] Artifactory response: 200 
11:18:33 [Debug] The Artifactory version is: 7.41.7
11:18:33 [Debug] Sending HTTP POST request to: https://artifactory.dev.example.com/artifactory/api/system/usage
11:18:33 [Debug] Usage Report: Artifactory response: 200 
11:18:33 [Debug] Usage Report: Usage info sent successfully.
11:18:33 [Debug] Created temp working directory: /tmp/jfrog.cli.temp.-1663496313-2285574178
11:18:33 [Debug] Downloading INFRA/xray-test , branch:refs/heads/pr_test to:/tmp/jfrog.cli.temp.-1663496313-2285574178
11:18:33 [Debug] Downloading repository completed
11:18:33 [🔵Info] Auditing /tmp/jfrog.cli.temp.-1663496313-2285574178
11:18:33 [🔵Info] Detected: pip.
11:18:34 [Debug] Running 'pip install .'
11:18:36 [🚨Error] pip Audit command failed: failed running command: '/tmp/jfrog.cli.temp.-1663496313-1268798988/venvdir/bin/python python /data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py --json' with error: exit status 1 - Traceback (most recent call last):
  File "/data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py", line 874, in <module>
    sys.exit(main())
  File "/data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py", line 822, in main
    user_only=args.user_only)
  File "/data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py", line 801, in get_installed_distributions
    from pip._internal.utils import misc
ImportError: No module named _internal.utils

11:18:36 [🚨Error] pip Audit command failed: failed running command: '/tmp/jfrog.cli.temp.-1663496313-1268798988/venvdir/bin/python python /data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py --json' with error: exit status 1 - Traceback (most recent call last):
  File "/data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py", line 874, in <module>
    sys.exit(main())
  File "/data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py", line 822, in main
    user_only=args.user_only)
  File "/data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py", line 801, in get_installed_distributions
    from pip._internal.utils import misc
ImportError: No module named _internal.utils
```

**Comment by sverdlov93** [comment]
Hi @optiz0r,
Can you please try running again with the latest version?
Also, can you tell if 'python' is linked to python 3 or python 2 on your machine? and if 'python3' exists as an alias?

**Comment by optiz0r** [comment]
This is a CentOS 7 machine, so `python` is an alias for `python2.7`. `python3` does also exist as an alias for `python3.6`
The same stack trace is raised using frogbot v2.3.3.

```
-bash-4.2$ ./frogbot --version
Frogbot version 2.3.3
-bash-4.2$ env JFROG_CLI_LOG_LEVEL=DEBUG JF_GIT_API_ENDPOINT="http://stash.example.com/rest" JF_GIT_OWNER=INFRA JF_GIT_REPO=xray-test  JF_URL=https://artifactory.dev.example.com ./frogbot scan-pull-requests
11:37:24 [🔵Info] Running Frogbot "scan-pull-requests" command 
11:37:24 [Debug] Usage Report: Sending info...
11:37:24 [Debug] Sending HTTP GET request to: https://artifactory.dev.example.com/artifactory/api/system/version
11:37:24 [Debug] Artifactory response: 200 
11:37:24 [Debug] JFrog Artifactory version is: 7.41.7
11:37:24 [Debug] Sending HTTP POST request to: https://artifactory.dev.example.com/artifactory/api/system/usage
11:37:24 [Debug] Usage Report: Artifactory response: 200 
11:37:24 [Debug] Usage Report: Usage info sent successfully.
11:37:24 [Debug] Created temp working directory: /tmp/jfrog.cli.temp.-1663843044-3687576375
11:37:24 [Debug] Downloading INFRA/xray-test , branch:refs/heads/pr_test to:/tmp/jfrog.cli.temp.-1663843044-3687576375
11:37:24 [Debug] Downloading repository completed
11:37:24 [🔵Info] Auditing /tmp/jfrog.cli.temp.-1663843044-3687576375
11:37:24 [🔵Info] Detected: pip.
11:37:25 [Debug] Running 'pip install .'
11:37:27 [🚨Error] 'pip' audit command failed:
failed running command: '/tmp/jfrog.cli.temp.-1663843044-4010744539 python /data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py --json' with error: exit status 1 - Traceback (most recent call last):
  File "/data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py", line 874, in <module>
    sys.exit(main())
  File "/data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py", line 822, in main
    user_only=args.user_only)
  File "/data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py", line 801, in get_installed_distributions
    from pip._internal.utils import misc
ImportError: No module named _internal.utils

11:37:27 [🚨Error] 'pip' audit command failed:
failed running command: '/tmp/jfrog.cli.temp.-1663843044-4010744539 python /data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py --json' with error: exit status 1 - Traceback (most recent call last):
  File "/data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py", line 874, in <module>
    sys.exit(main())
  File "/data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py", line 822, in main
    user_only=args.user_only)
  File "/data/jenkins/.jfrog/dependencies/pip/5/pipdeptree.py", line 801, in get_installed_distributions
    from pip._internal.utils import misc
ImportError: No module named _internal.utils
```

**Comment by sverdlov93** [comment]
@optiz0r 
I see, so it looks like it's using python2 instead of 3 because we are searching for 'python3' inside the PATH and when we can't find it we are trying to search for 'python', which is in your case python2.
Can you rename the python3 executable to 'python3', 
or add a symbolic link with the name python3 to the python3 executable?

**Comment by optiz0r** [comment]
@sverdlov93 python3 should be resolvable without any changes:

```
-bash-4.2$ which python3
/bin/python3
-bash-4.2$ file /bin/python3
/bin/python3: symbolic link to `python3.6'
-bash-4.2$ which python3.6
/bin/python3.6
-bash-4.2$ file /bin/python3.6
/bin/python3.6: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=f3bae17c0dd0d4df48daf95d5674cbda3327823a, stripped
```

If you are preferring `python3` over `python`, it's not clear why python2 is being used.

**Comment by sverdlov93** [comment]
Oh, I thought that maybe you don't have a python3 symbolic link but I see that you do.
Do you have 'virtualenv' on your machine?

**Comment by optiz0r** [comment]
@sverdlov93 I do, yes

```
-bash-4.2$ which virtualenv
/bin/virtualenv
-bash-4.2$ file /bin/virtualenv
/bin/virtualenv: C++ source, ASCII text
```

Content is
```
#!/usr/bin/python
import virtualenv
virtualenv.main()
```

So it will be invoked with python 2.7.5

**Comment by sverdlov93** [comment]
Following a discussion with @optiz0r the above issue was related to a very old `pip` version (9.0.3) and `virtualenv` version.
After upgrading them to the latest, Frogbot ran successfully.
We will improve our logs to prevent confusion in the future.

**Comment by optiz0r** [comment]
If anyone else finds themselves in the same position (namely running on EL7 or EL8 which ship py3.6 and old pip/virtualenv), it's not necessary to replace the system packages. Running frogbot within a virutalenv which has had pip and virtualenv packages updated within it to the latest version is sufficient.

```bash
python3 -m venv frogbot-env
source frogbot-env/bin/activate
pip install --upgrade pip virtualenv
frogbot ...
```
